version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_MULTIPLE_DATABASES: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./create-multiple-databases.sh:/docker-entrypoint-initdb.d/create-multiple-databases.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 3s
      retries: 40

volumes:
  postgres-data:
    name: postgres-data