[project]
name = "social-surveys-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apitally[litestar]>=0.14.2",
    "litestar>=2.13.0",
    "sqlalchemy>=2.0.36",
    "uvicorn>=0.32.1",
]
