"""init_table_user_admin

Revision ID: 39aac7d76d25
Revises: fb1ea7eaa7b8
Create Date: 2025-03-11 21:29:20.445895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39aac7d76d25'
down_revision: Union[str, None] = 'fb1ea7eaa7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
