"""create written answer table

Revision ID: 44cc2e741554
Revises: 0f52d3ac940e
Create Date: 2025-04-02 23:39:24.726471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44cc2e741554'
down_revision: Union[str, None] = '0f52d3ac940e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('written_answer',
    sa.Column('text', sa.String(), nullable=False, comment='Текст ответа на вопрос'),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Идентификатор записи'),
    sa.ForeignKeyConstraint(['question_id'], ['questionnaire_question.id'], ),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'telegram_user_id', name='uq_question_id_telegram_user_id'),
    comment='Таблица для хранения ответа на письменный вопрос'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('written_answer')
    # ### end Alembic commands ###
