name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: | 
        uv venv --python ${{ matrix.python-version }}
        source .venv/bin/activate
        uv sync  --no-cache

    - name: Run Ruff
      run: uv run ruff check src main.py

    - name: Run MyPy
      run: uv run mypy src main.py